version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://192.168.88.230:43333/api}
        VITE_API_KEY: ${VITE_API_KEY:-kent1023}
    ports:
      - "8080:80"
    restart: always
